version: 2
jobs:
  prepare:
    docker:
      - image: circleci/node:lts
    working_directory: ~/app-container
    steps:
      - checkout
      - save_cache: # saving initial checkout version to work with in next jobs
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/circleci-demo-workflows
      - run:
          name: Update npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install deps
          command: npm install
      - save_cache: # saving installed dependencies to new cache
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
  test:
    docker:
      - image: circleci/node:lts
    working_directory: ~/app-container
    steps:
      - restore_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run: 
          name: Running linter
          command: npm run lint
      - run:
          name: Running tests
          command: npm run test
  build:
    docker:
      - image: circleci/node:lts
    working_directory: ~/app-container
    steps:
      - restore_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Build artifact
          command: npm run build
      - store_artifacts:
          path: ~/app-container/easy-fetch/dist
          destination: artifact

workflows:
  version: 2
  test-build:
    jobs:
      - prepare
      - test:
          requires:
            - prepare
      - build:
          requires:
            - test